apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets
  labels:
    app.kubernetes.io/component: secrets
spec:
  template:
    metadata:
      name: modulo-secrets
      labels:
        app.kubernetes.io/component: secrets
    type: Opaque
  encryptedData:
    SECRET_KEY: ""
    FERNET_KEY: ""
    DATABASE_URL: ""
    REDIS_URL: ""
    POSTGRES_PASSWORD: ""
