FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG VITE_API_URL=""
ENV VITE_API_URL=${VITE_API_URL}
RUN npm run build

FROM nginx:1.27-alpine
RUN apk add --no-cache tzdata ca-certificates
COPY --from=build /app/dist /usr/share/nginx/html
COPY deploy/k8s/base/nginx-config.yaml /tmp/nginx-template
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
