/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        pending: 'var(--pending)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        ink: {
          50: '#E8EDF2',
          100: '#C5CDD8',
          200: '#9CA6B5',
          300: '#7B8794',
          400: '#5A6673',
          500: '#3D4852',
          600: '#262E38',
          700: '#1E2630',
          800: '#12171F',
          900: '#0B0E14',
          950: '#06080C',
        },
        teal: {
          50: '#E6FFFA',
          100: '#B3FFE8',
          200: '#80FFD9',
          300: '#4DFFCB',
          400: '#1AFFBD',
          500: '#00FFD1',
          600: '#00CCA8',
          700: '#009980',
          800: '#006658',
          900: '#003330',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
    },
  },
  plugins: [],
}
