/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        success: 'hsl(var(--success))',
        warning: 'hsl(var(--warning))',
        pending: 'hsl(var(--pending))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        ink: {
          50: '#E8EDF2',
          100: '#C5CDD8',
          200: '#9CA6B5',
          300: '#7B8794',
          400: '#5A6673',
          500: '#3D4852',
          600: '#262E38',
          700: '#1E2630',
          800: '#12171F',
          900: '#0B0E14',
          950: '#06080C',
        },
        teal: {
          50: '#E6FFFA',
          100: '#B3FFE8',
          200: '#80FFD9',
          300: '#4DFFCB',
          400: '#1AFFBD',
          500: '#00FFD1',
          600: '#00CCA8',
          700: '#009980',
          800: '#006658',
          900: '#003330',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
    },
  },
  plugins: [],
}
