apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "modulo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modulo.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "modulo.nginx.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modulo.labels" . | nindent 4 }}
data:
  default.conf: |
    {{- include "modulo.nginx.config" . | nindent 4 }}
