{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "modulo.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modulo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "modulo.backend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "modulo.frontend.selectorLabels" . | nindent 14 }}
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 8000
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Release.Name }}-postgresql
      ports:
        - port: 5432
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Release.Name }}-redis-master
      ports:
        - port: 6379
          protocol: TCP
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "modulo.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modulo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "modulo.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 80
          protocol: TCP
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
