{{- if .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "modulo.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modulo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "modulo.backend.selectorLabels" . | nindent 6 }}
{{- end }}
{{- if .Values.frontend.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "modulo.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modulo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "modulo.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
