{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "modulo.backend.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modulo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  {{- if .Values.secrets.SECRET_KEY }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc | quote }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.FERNET_KEY }}
  FERNET_KEY: {{ .Values.secrets.FERNET_KEY | b64enc | quote }}
  {{- else }}
  FERNET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.DATABASE_URL }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  {{- else if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://%s:$(DATABASE_PASSWORD)@%s-postgresql.%s.svc.cluster.local:5432/%s" .Values.postgresql.auth.username .Release.Name .Release.Namespace .Values.postgresql.auth.database | b64enc | quote }}
  {{- else }}
  DATABASE_URL: ""
  {{- end }}
  {{- if .Values.secrets.REDIS_URL }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL | b64enc | quote }}
  {{- else if .Values.redis.enabled }}
  REDIS_URL: {{ printf "redis://:%s@%s-redis-master.%s.svc.cluster.local:6379" .Values.redis.auth.password .Release.Name .Release.Namespace | b64enc | quote }}
  {{- else }}
  REDIS_URL: ""
  {{- end }}
{{- end }}
