FROM python:3.12-slim AS builder
WORKDIR /app
COPY backend/pyproject.toml backend/uv.lock ./
RUN pip install uv --no-cache-dir && uv sync --no-dev --frozen --no-cache

FROM python:3.12-slim AS runtime
RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/.venv ./.venv
COPY backend/src ./src
COPY backend/alembic.ini ./alembic.ini
COPY backend/migrations ./migrations
COPY backend/entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh
ENV PATH="/app/.venv/bin:$PATH"
EXPOSE 8000
CMD ["./entrypoint.sh"]
