app = 'demo-modulo'
primary_region = 'lhr'

[build]
  dockerfile = "backend/Dockerfile.fly"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  MODULO_DB = "postgres"
  MODULO_PUBLIC_URL = "https://demo.modulo.run"
  MODULO_DEMO_MODE = "true"
  MODULO_PLUGIN_DISCOVERY = "false"
  MODULO_MAX_LOCAL_CONCURRENCY = "4"
  REDIS_URL = ""

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
