apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "modulo.fullname" . }}-config
  namespace: {{ include "modulo.namespace" . }}
  labels:
    {{- include "modulo.labels" . | nindent 4 }}
data:
  MODULO_DB: "{{ .Values.backend.env.MODULO_DB | default "postgres" }}"
  MODULO_LOG_LEVEL: "{{ .Values.backend.env.MODULO_LOG_LEVEL | default "info" }}"
  MODULO_ENV: "{{ .Values.backend.env.MODULO_ENV | default "production" }}"
  MODULO_PUBLIC_URL: "{{ .Values.backend.env.MODULO_PUBLIC_URL | default "http://localhost:8000" }}"
  MODULO_MAX_LOCAL_CONCURRENCY: "{{ .Values.backend.env.MODULO_MAX_LOCAL_CONCURRENCY | default "2" }}"
  CORS_ORIGINS: "{{ .Values.backend.env.CORS_ORIGINS | default "http://localhost:5173" }}"
  MODULO_PLUGIN_DISCOVERY: "{{ .Values.backend.env.MODULO_PLUGIN_DISCOVERY | default "false" }}"
