"""Organisation ORM model contract tests (FAR-872 regression).

The Organisation model deliberately does NOT use TimestampMixin — it declares
``created_at`` only, with no ``updated_at``. This is documented in
db/seed_demo.py ("Organisation carries no ``updated_at``") and enforced by
migration 0243_remove_organisations_audit_drift which drops the DB columns.

These unit tests guard the ORM half of the contract: they prevent
re-introduction of ``updated_at`` (or other orphaned audit columns) on the
Organisation mapper. The DB half — that every mapped column actually exists in
the migrated schema — cannot be asserted at unit level (comparing
``sa_inspect(Organisation).columns`` with ``Organisation.__table__.columns`` is
a tautology) and lives in
``tests/integration/db/test_organisation_model_contract.py``, which reflects the
real migrated ``organisations`` table.
"""

import pytest
from sqlalchemy import inspect as sa_inspect

from modulo.db.models.organisation import Organisation


@pytest.mark.parametrize("column", ["updated_at", "updated_by", "deleted_by"])
def test_organisation_declares_no_audit_columns(column: str) -> None:
    """Organisation must not map the audit columns dropped on main.

    Regression test for FAR-872: the mapper declared an audit column the
    migrated DB did not have, so every ``select(Organisation)`` raised
    ``ProgrammingError: column organisations.updated_at does not exist``.
    Migration 0233 added ``updated_at``/``updated_by``/``deleted_by`` (0239 was
    a no-op) and migration 0243_remove_organisations_audit_drift removes them —
    matching this non-declaration.
    """
    column_names = {c.key for c in sa_inspect(Organisation).columns}
    assert column not in column_names, (
        f"Organisation must not declare {column} — "
        "see seed_demo.py and migration 0243. "
        f"Currently mapped columns: {sorted(column_names)}"
    )


def test_select_organisation_sql_omits_updated_at() -> None:
    """The SQL generated by ``select(Organisation)`` must not reference ``updated_at``.

    Regression test for FAR-872: this catches the case where a future change
    re-introduces ``updated_at`` on the ORM or injects it via a dynamic
    column builder.
    """
    from sqlalchemy import select

    stmt = select(Organisation)
    compiled = stmt.compile()
    sql_lower = compiled.string.lower()
    assert "updated_at" not in sql_lower, (
        f"select(Organisation) must not reference updated_at in generated SQL. Generated SQL: {compiled.string}"
    )


def test_organisation_declares_created_at() -> None:
    """Organisation's ``created_at`` must be present on the mapper.

    Organisation intentionally does NOT use TimestampMixin (which provides both
    ``created_at`` and ``updated_at``), so it declares ``created_at`` directly.
    The guard that ``updated_at`` is absent (the mixin's other column) lives in
    ``test_organisation_declares_no_audit_columns``.
    """
    column_names = {c.key for c in sa_inspect(Organisation).columns}
    assert "created_at" in column_names
