import enum


class ModelBackendProvider(enum.StrEnum):
    ANTHROPIC = "anthropic"
    OPENAI = "openai"
    AZURE_OPENAI = "azure_openai"
    BEDROCK = "bedrock"
    OLLAMA = "ollama"
    CUSTOM = "custom"
    GROQ = "groq"
    DEEPSEEK = "deepseek"
    OPENROUTER = "openrouter"
    TOGETHERAI = "togetherai"
    PERPLEXITY = "perplexity"
    FIREWORKS = "fireworks"
    GROK = "grok"
    QWEN = "qwen"
    AI21 = "ai21"
    VLLM = "vllm"
    TGI = "tgi"
    LM_STUDIO = "lm_studio"
    JAN = "jan"
    LOCALAI = "localai"
    LLAMACPP = "llamacpp"
    COHERE = "cohere"
    MISTRAL = "mistral"
    GEMINI = "gemini"
    REPLICATE = "replicate"
    VERTEXAI = "vertexai"
    WATSONX = "watsonx"
