"""22 built-in library schema definitions as JSON Schema objects.

Each entry has a ``name`` (URL-safe slug), ``description``, and
``definition`` (a valid Draft 2020-12 JSON Schema).
"""

SCHEMAS: list[dict[str, object]] = [
    {
        "name": "meeting-notes",
        "description": "Structured meeting notes with agenda, decisions, and action items",
        "definition": {
            "title": "Meeting Notes",
            "description": "Schema for structured meeting documentation",
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Meeting title"},
                "date": {"type": "string", "format": "date", "description": "Meeting date"},
                "attendees": {"type": "array", "items": {"type": "string"}, "description": "List of attendees"},
                "agenda": {"type": "array", "items": {"type": "string"}, "description": "Agenda items"},
                "discussion": {"type": "string", "description": "Discussion notes"},
                "decisions": {"type": "array", "items": {"type": "string"}, "description": "Decisions made"},
                "action-items": {"type": "array", "items": {"type": "string"}, "description": "Action items"},
                "next-meeting-date": {"type": "string", "format": "date", "description": "Next meeting date"},
            },
            "required": ["title", "date"],
        },
    },
    {
        "name": "adr",
        "description": "Architecture Decision Record for documenting architectural decisions",
        "definition": {
            "title": "Architecture Decision Record",
            "description": "Record of an architectural decision including context, decision, and consequences",
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "ADR title"},
                "status": {
                    "type": "string",
                    "enum": ["proposed", "accepted", "deprecated", "superseded"],
                    "description": "ADR status",
                },
                "context": {"type": "string", "description": "Context and motivation"},
                "decision": {"type": "string", "description": "The decision made"},
                "consequences": {"type": "string", "description": "Consequences of the decision"},
                "alternatives": {
                    "type": "array", "items": {"type": "string"},
                    "description": "Alternatives considered",
                },
                "date": {"type": "string", "format": "date", "description": "Decision date"},
                "deciders": {
                    "type": "array", "items": {"type": "string"},
                    "description": "People who made the decision",
                },
            },
            "required": ["title", "status", "decision"],
        },
    },
    {
        "name": "api-spec",
        "description": "API endpoint specification with request/response schemas",
        "definition": {
            "title": "API Specification",
            "description": "Definition of an API endpoint with request/response schemas and parameters",
            "type": "object",
            "properties": {
                "endpoint": {"type": "string", "description": "API endpoint path"},
                "method": {
                    "type": "string",
                    "enum": ["GET", "POST", "PUT", "DELETE", "PATCH"],
                    "description": "HTTP method",
                },
                "description": {"type": "string", "description": "Endpoint description"},
                "request-body": {"type": "object", "description": "Request body schema"},
                "response-body": {"type": "object", "description": "Response body schema"},
                "headers": {"type": "object", "description": "Request headers"},
                "query-params": {
                    "type": "array",
                    "items": {"type": "object"},
                    "description": "Query parameters",
                },
            },
            "required": ["endpoint", "method"],
        },
    },
    {
        "name": "design-doc",
        "description": "Technical design document for feature planning",
        "definition": {
            "title": "Design Document",
            "description": "Technical design document outlining goals, design, and implementation plan",
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Design document title"},
                "author": {"type": "string", "description": "Document author"},
                "status": {"type": "string", "description": "Document status"},
                "overview": {"type": "string", "description": "High-level overview"},
                "context": {"type": "string", "description": "Background and context"},
                "goals": {"type": "array", "items": {"type": "string"}, "description": "Design goals"},
                "non-goals": {"type": "array", "items": {"type": "string"}, "description": "Explicit non-goals"},
                "design": {"type": "string", "description": "Detailed design"},
                "implementation-plan": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Implementation steps",
                },
                "open-questions": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Open questions",
                },
            },
            "required": ["title", "author", "design"],
        },
    },
    {
        "name": "changelog-entry",
        "description": "Structured changelog entry following keepachangelog format",
        "definition": {
            "title": "Changelog Entry",
            "description": "A single changelog entry following keepachangelog conventions",
            "type": "object",
            "properties": {
                "version": {"type": "string", "description": "Semantic version"},
                "date": {"type": "string", "format": "date", "description": "Release date"},
                "type": {
                    "type": "string",
                    "enum": ["added", "changed", "deprecated", "removed", "fixed", "security"],
                    "description": "Change type",
                },
                "description": {"type": "string", "description": "Change description"},
                "issue-refs": {"type": "array", "items": {"type": "string"}, "description": "Issue references"},
                "pr-refs": {"type": "array", "items": {"type": "string"}, "description": "PR references"},
            },
            "required": ["version", "type", "description"],
        },
    },
    {
        "name": "release-note",
        "description": "Release notes for product releases",
        "definition": {
            "title": "Release Note",
            "description": "Release notes describing a product release",
            "type": "object",
            "properties": {
                "version": {"type": "string", "description": "Release version"},
                "date": {"type": "string", "format": "date", "description": "Release date"},
                "title": {"type": "string", "description": "Release title"},
                "summary": {"type": "string", "description": "Release summary"},
                "features": {"type": "array", "items": {"type": "string"}, "description": "New features"},
                "bug-fixes": {"type": "array", "items": {"type": "string"}, "description": "Bug fixes"},
                "breaking-changes": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Breaking changes",
                },
                "upgrade-notes": {"type": "string", "description": "Upgrade instructions"},
            },
            "required": ["version", "date", "title"],
        },
    },
    {
        "name": "test-plan",
        "description": "Test plan document for feature testing",
        "definition": {
            "title": "Test Plan",
            "description": "Test plan outlining test strategy, cases, and success criteria",
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Test plan title"},
                "feature": {"type": "string", "description": "Feature under test"},
                "test-cases": {"type": "array", "items": {"type": "string"}, "description": "Test case references"},
                "environment": {"type": "string", "description": "Test environment"},
                "preconditions": {"type": "string", "description": "Preconditions"},
                "success-criteria": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Success criteria",
                },
                "risks": {"type": "array", "items": {"type": "string"}, "description": "Identified risks"},
            },
            "required": ["title", "feature"],
        },
    },
    {
        "name": "test-case",
        "description": "Individual test case definition",
        "definition": {
            "title": "Test Case",
            "description": "Individual test case with steps, expected results, and test data",
            "type": "object",
            "properties": {
                "id": {"type": "string", "description": "Test case ID"},
                "title": {"type": "string", "description": "Test case title"},
                "description": {"type": "string", "description": "Test case description"},
                "preconditions": {"type": "array", "items": {"type": "string"}, "description": "Preconditions"},
                "steps": {"type": "array", "items": {"type": "string"}, "description": "Test steps"},
                "expected-results": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Expected results",
                },
                "test-data": {"type": "object", "description": "Test data"},
                "priority": {
                    "type": "string",
                    "enum": ["high", "medium", "low"],
                    "description": "Test priority",
                },
            },
            "required": ["id", "title", "steps", "expected-results"],
        },
    },
    {
        "name": "db-change",
        "description": "Database schema change record",
        "definition": {
            "title": "Database Change",
            "description": "Record of a database schema migration or change",
            "type": "object",
            "properties": {
                "migration-id": {"type": "string", "description": "Migration identifier"},
                "description": {"type": "string", "description": "Change description"},
                "author": {"type": "string", "description": "Change author"},
                "date": {"type": "string", "format": "date", "description": "Change date"},
                "affected-tables": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Affected tables",
                },
                "sql": {"type": "string", "description": "Migration SQL"},
                "rollback-sql": {"type": "string", "description": "Rollback SQL"},
                "risk": {
                    "type": "string",
                    "enum": ["low", "medium", "high"],
                    "description": "Change risk level",
                },
            },
            "required": ["migration-id", "description", "sql", "rollback-sql"],
        },
    },
    {
        "name": "sprint-plan",
        "description": "Sprint plan for agile development",
        "definition": {
            "title": "Sprint Plan",
            "description": "Sprint plan with goals, tickets, capacity, and team assignments",
            "type": "object",
            "properties": {
                "sprint-name": {"type": "string", "description": "Sprint name"},
                "start-date": {"type": "string", "format": "date", "description": "Sprint start date"},
                "end-date": {"type": "string", "format": "date", "description": "Sprint end date"},
                "goals": {"type": "array", "items": {"type": "string"}, "description": "Sprint goals"},
                "tickets": {"type": "array", "items": {"type": "string"}, "description": "Ticket references"},
                "capacity": {"type": "number", "description": "Team capacity"},
                "team": {"type": "array", "items": {"type": "string"}, "description": "Team members"},
                "risks": {"type": "array", "items": {"type": "string"}, "description": "Identified risks"},
            },
            "required": ["sprint-name", "start-date", "end-date"],
        },
    },
    {
        "name": "roadmap-item",
        "description": "Product roadmap item",
        "definition": {
            "title": "Roadmap Item",
            "description": "Product roadmap item with priority, status, and dependencies",
            "type": "object",
            "properties": {
                "quarter": {"type": "string", "description": "Target quarter"},
                "title": {"type": "string", "description": "Item title"},
                "description": {"type": "string", "description": "Item description"},
                "priority": {
                    "type": "string",
                    "enum": ["p0", "p1", "p2", "p3"],
                    "description": "Priority level",
                },
                "status": {
                    "type": "string",
                    "enum": ["planned", "in-progress", "completed", "cancelled"],
                    "description": "Item status",
                },
                "dependencies": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Dependencies",
                },
                "owner": {"type": "string", "description": "Item owner"},
            },
            "required": ["quarter", "title", "priority"],
        },
    },
    {
        "name": "quality-report",
        "description": "Quality assurance report",
        "definition": {
            "title": "Quality Report",
            "description": "Quality assurance report with metrics, regressions, and recommendations",
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Report title"},
                "date": {"type": "string", "format": "date", "description": "Report date"},
                "period": {"type": "string", "description": "Reporting period"},
                "metrics": {"type": "object", "description": "Quality metrics"},
                "regressions": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Regressions found",
                },
                "improvements": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Improvements made",
                },
                "recommendations": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Recommendations",
                },
            },
            "required": ["title", "date", "period"],
        },
    },
    {
        "name": "deployment",
        "description": "Deployment record",
        "definition": {
            "title": "Deployment",
            "description": "Record of a deployment to staging or production",
            "type": "object",
            "properties": {
                "version": {"type": "string", "description": "Deployed version"},
                "environment": {
                    "type": "string",
                    "enum": ["staging", "production"],
                    "description": "Target environment",
                },
                "date": {"type": "string", "format": "date-time", "description": "Deployment date"},
                "status": {
                    "type": "string",
                    "enum": ["pending", "in-progress", "completed", "rolled-back"],
                    "description": "Deployment status",
                },
                "changes": {"type": "array", "items": {"type": "string"}, "description": "Changes deployed"},
                "verification-steps": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Verification steps",
                },
                "rollback-plan": {"type": "string", "description": "Rollback plan"},
            },
            "required": ["version", "environment", "status"],
        },
    },
    {
        "name": "incident-report",
        "description": "Incident report for production incidents",
        "definition": {
            "title": "Incident Report",
            "description": "Incident report with timeline, root cause, and resolution",
            "type": "object",
            "properties": {
                "id": {"type": "string", "description": "Incident ID"},
                "title": {"type": "string", "description": "Incident title"},
                "severity": {"type": "string", "description": "Incident severity"},
                "date": {"type": "string", "format": "date-time", "description": "Incident date"},
                "status": {
                    "type": "string",
                    "enum": ["investigating", "identified", "monitoring", "resolved"],
                    "description": "Incident status",
                },
                "summary": {"type": "string", "description": "Incident summary"},
                "timeline": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Incident timeline",
                },
                "root-cause": {"type": "string", "description": "Root cause"},
                "resolution": {"type": "string", "description": "Resolution"},
                "prevention": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Prevention measures",
                },
            },
            "required": ["id", "title", "severity", "date"],
        },
    },
    {
        "name": "env-config",
        "description": "Environment configuration record",
        "definition": {
            "title": "Environment Configuration",
            "description": "Configuration variables and secrets for a service environment",
            "type": "object",
            "properties": {
                "environment": {"type": "string", "description": "Environment name"},
                "service": {"type": "string", "description": "Service name"},
                "variables": {"type": "object", "description": "Configuration variables"},
                "secrets-refs": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Secret references",
                },
                "dependencies": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Service dependencies",
                },
                "version": {"type": "string", "description": "Config version"},
            },
            "required": ["environment", "service"],
        },
    },
    {
        "name": "okr",
        "description": "Objectives and Key Results",
        "definition": {
            "title": "OKR",
            "description": "Objectives and Key Results for a quarter",
            "type": "object",
            "properties": {
                "quarter": {"type": "string", "description": "Target quarter"},
                "objective": {"type": "string", "description": "The objective"},
                "key-results": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Key results",
                },
                "owner": {"type": "string", "description": "OKR owner"},
                "team": {"type": "string", "description": "Team name"},
                "progress": {"type": "number", "description": "Progress percentage"},
                "status": {
                    "type": "string",
                    "enum": ["on-track", "at-risk", "behind", "not-started"],
                    "description": "OKR status",
                },
            },
            "required": ["quarter", "objective", "key-results"],
        },
    },
    {
        "name": "post-mortem",
        "description": "Incident post-mortem document",
        "definition": {
            "title": "Post-Mortem",
            "description": "Post-incident analysis with timeline, root cause, and action items",
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Post-mortem title"},
                "date": {"type": "string", "format": "date", "description": "Document date"},
                "incident-ref": {"type": "string", "description": "Incident reference"},
                "summary": {"type": "string", "description": "Incident summary"},
                "timeline": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Event timeline",
                },
                "root-cause-analysis": {"type": "string", "description": "Root cause analysis"},
                "what-went-well": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "What went well",
                },
                "what-went-wrong": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "What went wrong",
                },
                "action-items": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Action items",
                },
            },
            "required": ["title", "incident-ref"],
        },
    },
    {
        "name": "code-review-comment",
        "description": "Code review comment",
        "definition": {
            "title": "Code Review Comment",
            "description": "Comment on a code review with severity and resolution status",
            "type": "object",
            "properties": {
                "file": {"type": "string", "description": "File path"},
                "line-start": {"type": "integer", "description": "Start line"},
                "line-end": {"type": "integer", "description": "End line"},
                "severity": {"type": "string", "description": "Comment severity"},
                "category": {"type": "string", "description": "Comment category"},
                "comment": {"type": "string", "description": "Comment text"},
                "author": {"type": "string", "description": "Comment author"},
                "resolved": {"type": "boolean", "description": "Whether resolved"},
                "resolution": {"type": "string", "description": "Resolution notes"},
            },
            "required": ["file", "comment", "author"],
        },
    },
    {
        "name": "bug-report",
        "description": "Bug report for tracking software defects",
        "definition": {
            "title": "Bug Report",
            "description": "Bug report with reproduction steps, expected and actual behavior",
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Bug title"},
                "description": {"type": "string", "description": "Bug description"},
                "steps-to-reproduce": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Reproduction steps",
                },
                "expected-behavior": {"type": "string", "description": "Expected behavior"},
                "actual-behavior": {"type": "string", "description": "Actual behavior"},
                "environment": {"type": "string", "description": "Environment details"},
                "severity": {"type": "string", "description": "Bug severity"},
                "priority": {"type": "string", "description": "Bug priority"},
                "assignee": {"type": "string", "description": "Assigned person"},
                "status": {"type": "string", "description": "Bug status"},
            },
            "required": ["title", "description", "steps-to-reproduce", "expected-behavior", "actual-behavior"],
        },
    },
    {
        "name": "issue-ticket",
        "description": "Generic issue ticket",
        "definition": {
            "title": "Issue Ticket",
            "description": "Generic issue ticket for tracking bugs, features, and chores",
            "type": "object",
            "properties": {
                "id": {"type": "string", "description": "Ticket ID"},
                "title": {"type": "string", "description": "Ticket title"},
                "description": {"type": "string", "description": "Ticket description"},
                "type": {
                    "type": "string",
                    "enum": ["bug", "feature", "enhancement", "chore"],
                    "description": "Ticket type",
                },
                "priority": {"type": "string", "description": "Ticket priority"},
                "status": {"type": "string", "description": "Ticket status"},
                "assignee": {"type": "string", "description": "Assigned person"},
                "labels": {"type": "array", "items": {"type": "string"}, "description": "Labels"},
                "sprint": {"type": "string", "description": "Sprint name"},
                "story-points": {"type": "number", "description": "Story points"},
            },
            "required": ["id", "title", "type"],
        },
    },
    {
        "name": "pull-request",
        "description": "Pull request record",
        "definition": {
            "title": "Pull Request",
            "description": "Pull request with changes, reviewers, and CI check results",
            "type": "object",
            "properties": {
                "id": {"type": "string", "description": "PR ID/number"},
                "title": {"type": "string", "description": "PR title"},
                "description": {"type": "string", "description": "PR description"},
                "source-branch": {"type": "string", "description": "Source branch"},
                "target-branch": {"type": "string", "description": "Target branch"},
                "author": {"type": "string", "description": "PR author"},
                "reviewers": {"type": "array", "items": {"type": "string"}, "description": "Reviewers"},
                "status": {
                    "type": "string",
                    "enum": ["open", "draft", "merged", "closed"],
                    "description": "PR status",
                },
                "changes": {"type": "object", "description": "Change stats"},
                "checks": {
                    "type": "array",
                    "items": {"type": "object"},
                    "description": "CI check results",
                },
            },
            "required": ["id", "title", "author", "source-branch", "target-branch"],
        },
    },
    {
        "name": "user-story",
        "description": "User story for agile requirements",
        "definition": {
            "title": "User Story",
            "description": "User story with acceptance criteria, story points, and sprint assignment",
            "type": "object",
            "properties": {
                "id": {"type": "string", "description": "Story ID"},
                "title": {"type": "string", "description": "Story title"},
                "description": {"type": "string", "description": "Story description"},
                "acceptance-criteria": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Acceptance criteria",
                },
                "story-points": {"type": "number", "description": "Story points"},
                "priority": {"type": "string", "description": "Story priority"},
                "epic": {"type": "string", "description": "Parent epic"},
                "sprint": {"type": "string", "description": "Sprint name"},
                "assignee": {"type": "string", "description": "Assigned person"},
                "status": {"type": "string", "description": "Story status"},
            },
            "required": ["id", "title", "description", "acceptance-criteria"],
        },
    },
]
