apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: ingress-patch.yaml

namespace: modulo-prod

commonAnnotations:
  app.kubernetes.io/environment: production
  app.kubernetes.io/version: latest

configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - MODULO_PUBLIC_URL=https://modulo.example.com
      - CORS_ORIGINS=https://modulo.example.com
      - MODULO_DEMO_MODE=false
