"""Create the immutable initial Modulo domain schema.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-19
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TENANT_REFERENCES = (
    ("agents", "created_by", "users"),
    ("agents", "input_schema_id", "schemas"),
    ("agents", "library_id", "library_primitives"),
    ("agents", "model_backend_id", "model_backends"),
    ("agents", "output_schema_id", "schemas"),
    ("audit_events", "actor_user_id", "users"),
    ("connector_instances", "owner_id", "users"),
    ("connector_instances", "owner_team_id", "teams"),
    ("hitl_claims", "claimed_by", "users"),
    ("hitl_claims", "pipeline_id", "pipelines"),
    ("hitl_claims", "run_id", "runs"),
    ("library_primitives", "created_by", "users"),
    ("library_primitives", "forked_from", "library_primitives"),
    ("library_primitives", "owner_team_id", "teams"),
    ("model_backends", "created_by", "users"),
    ("model_backends", "owner_team_id", "teams"),
    ("notification_delivery_log", "run_id", "runs"),
    ("org_api_keys", "created_by", "users"),
    ("org_api_keys", "team_id", "teams"),
    ("pipeline_edges", "pipeline_id", "pipelines"),
    ("pipeline_snapshots", "created_by", "users"),
    ("pipeline_snapshots", "pipeline_id", "pipelines"),
    ("pipelines", "created_by", "users"),
    ("pipelines", "owner_team_id", "teams"),
    ("pipelines", "stage_id", "stages"),
    ("runs", "created_by", "users"),
    ("runs", "pipeline_id", "pipelines"),
    ("runs", "snapshot_id", "pipeline_snapshots"),
    ("runs", "trigger_id", "triggers"),
    ("schema_versions", "created_by", "users"),
    ("schema_versions", "schema_id", "schemas"),
    ("schemas", "created_by", "users"),
    ("stages", "created_by", "users"),
    ("stages", "owner_team_id", "teams"),
    ("teams", "created_by", "users"),
    ("trigger_events", "run_id", "runs"),
    ("trigger_events", "trigger_id", "triggers"),
    ("triggers", "created_by", "users"),
    ("triggers", "pipeline_id", "pipelines"),
    ("webhook_dedup_hashes", "trigger_id", "triggers"),
    ("webhook_payloads", "trigger_event_id", "trigger_events"),
)

_TENANT_REFERENCE_FUNCTION = """
CREATE FUNCTION enforce_same_organisation() RETURNS trigger AS $$
DECLARE
    referenced_id uuid;
    referenced_organisation_id uuid;
    child_organisation_id uuid;
BEGIN
    referenced_id := (to_jsonb(NEW) ->> TG_ARGV[1])::uuid;
    IF referenced_id IS NULL THEN
        RETURN NEW;
    END IF;
    child_organisation_id := (to_jsonb(NEW) ->> 'organisation_id')::uuid;
    EXECUTE format('SELECT organisation_id FROM %I WHERE id = $1', TG_ARGV[0])
        INTO referenced_organisation_id USING referenced_id;
    IF referenced_organisation_id IS NULL OR referenced_organisation_id <> child_organisation_id
    THEN
        RAISE EXCEPTION 'cross-organisation reference from %.% to %',
            TG_TABLE_NAME, TG_ARGV[1], TG_ARGV[0]
            USING ERRCODE = '23503';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def _create_tenant_reference_guards() -> None:
    op.execute(sa.text(_TENANT_REFERENCE_FUNCTION))
    for child_table, child_column, parent_table in _TENANT_REFERENCES:
        trigger_name = f"trg_{child_table}_{child_column}_tenant"
        op.execute(
            sa.text(
                f'CREATE TRIGGER "{trigger_name}" BEFORE INSERT OR UPDATE OF "{child_column}", '
                f'"organisation_id" ON "{child_table}" FOR EACH ROW EXECUTE FUNCTION '
                f"enforce_same_organisation('{parent_table}', '{child_column}')"
            )
        )


_LIBRARY_FORK_FUNCTION = """
CREATE FUNCTION enforce_library_fork_provenance() RETURNS trigger AS $$
DECLARE
    parent_source text;
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.forked_from IS DISTINCT FROM NEW.forked_from THEN
        RAISE EXCEPTION 'library primitive forked_from is immutable'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.forked_from IS NOT NULL THEN
        SELECT source INTO parent_source
        FROM library_primitives
        WHERE id = NEW.forked_from;
        IF parent_source IS DISTINCT FROM 'registry' THEN
            RAISE EXCEPTION 'forked_from must reference a registry primitive'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def _create_library_fork_guard() -> None:
    op.execute(sa.text(_LIBRARY_FORK_FUNCTION))
    op.execute(
        sa.text(
            "CREATE TRIGGER trg_library_primitives_fork_provenance "
            "BEFORE INSERT OR UPDATE OF forked_from ON library_primitives "
            "FOR EACH ROW EXECUTE FUNCTION enforce_library_fork_provenance()"
        )
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column("plan_id", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'deleted')", name="ck_organisations_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "org_daily_run_counts",
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("run_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "total_spend_usd", sa.Numeric(precision=14, scale=6), server_default="0", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "run_date", name="uq_org_daily_run_counts_date"),
    )
    op.create_index(
        op.f("ix_org_daily_run_counts_organisation_id"),
        "org_daily_run_counts",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("org_role", sa.String(length=20), server_default="runner", nullable=False),
        sa.Column("auth_provider", sa.String(length=20), server_default="local", nullable=False),
        sa.Column("sso_subject", sa.String(length=512), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "auth_provider IN ('local', 'oidc', 'saml')", name="ck_users_auth_provider"
        ),
        sa.CheckConstraint(
            "org_role IN ('admin', 'operator', 'runner', 'viewer')", name="ck_users_org_role"
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "email", name="uq_users_organisation_email"),
    )
    op.create_index(op.f("ix_users_organisation_id"), "users", ["organisation_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_organisation_id"), "audit_events", ["organisation_id"], unique=False
    )
    op.create_table(
        "schemas",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("abstract_name", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "name", name="uq_schemas_organisation_name"),
    )
    op.create_index(
        op.f("ix_schemas_organisation_id"), "schemas", ["organisation_id"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("notification_endpoints", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "name", name="uq_teams_organisation_name"),
    )
    op.create_index(op.f("ix_teams_organisation_id"), "teams", ["organisation_id"], unique=False)
    op.create_table(
        "connector_instances",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("connector_type_id", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("owner_team_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=10), server_default="org", nullable=False),
        sa.Column("credentials_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("allowed_operations", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_health_check_error", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility IN ('org', 'team')", name="ck_connector_instances_visibility"
        ),
        sa.CheckConstraint(
            "visibility = 'org' OR owner_team_id IS NOT NULL",
            name="ck_connector_instances_team_owner",
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connector_instances_connector_type_id"),
        "connector_instances",
        ["connector_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connector_instances_organisation_id"),
        "connector_instances",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "library_primitives",
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("primitive_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("forked_from", sa.UUID(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("ed25519_signature", sa.String(length=256), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=True),
        sa.Column("average_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("owner_team_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=10), server_default="org", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'local' AND source_url IS NULL AND checksum IS NULL "
            "AND ed25519_signature IS NULL AND verified IS NULL "
            "AND download_count IS NULL AND average_rating IS NULL AND review_count IS NULL) "
            "OR (source = 'registry' AND owner_team_id IS NULL AND visibility = 'org' "
            "AND forked_from IS NULL AND source_url IS NOT NULL AND checksum IS NOT NULL "
            "AND ed25519_signature IS NOT NULL AND verified IS NOT NULL "
            "AND download_count IS NOT NULL AND average_rating IS NOT NULL "
            "AND review_count IS NOT NULL)",
            name="ck_library_primitives_source_fields",
        ),
        sa.CheckConstraint(
            "primitive_type IN ('schema', 'workflow', 'agent', 'integration')",
            name="ck_library_primitives_type",
        ),
        sa.CheckConstraint("source IN ('local', 'registry')", name="ck_library_primitives_source"),
        sa.CheckConstraint(
            "visibility IN ('org', 'team')", name="ck_library_primitives_visibility"
        ),
        sa.CheckConstraint(
            "visibility = 'org' OR owner_team_id IS NOT NULL",
            name="ck_library_primitives_team_owner",
        ),
        sa.CheckConstraint(
            "average_rating IS NULL OR average_rating BETWEEN 1 AND 5",
            name="ck_library_primitives_rating",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["forked_from"], ["library_primitives.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id", "source", "slug", "version", name="uq_library_primitive_version"
        ),
    )
    op.create_index(
        op.f("ix_library_primitives_organisation_id"),
        "library_primitives",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "model_backends",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("credentials_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("default_params", sa.JSON(), nullable=False),
        sa.Column("cost_tracking", sa.String(length=10), server_default="enabled", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("owner_team_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=10), server_default="org", nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_health_check_error", sa.String(length=2000), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cost_tracking IN ('enabled', 'disabled')", name="ck_model_backends_cost"
        ),
        sa.CheckConstraint(
            "provider IN ('anthropic', 'openai', 'azure_openai', 'bedrock', 'ollama', 'custom')",
            name="ck_model_backends_provider",
        ),
        sa.CheckConstraint("visibility IN ('org', 'team')", name="ck_model_backends_visibility"),
        sa.CheckConstraint(
            "visibility = 'org' OR owner_team_id IS NOT NULL",
            name="ck_model_backends_team_owner",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_backends_organisation_id"),
        "model_backends",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "org_api_keys",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("lookup_prefix", sa.String(length=8), nullable=False),
        sa.Column("hashed_secret", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('operator', 'runner')", name="ck_org_api_keys_role"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lookup_prefix", name="uq_org_api_keys_lookup_prefix"),
    )
    op.create_index(
        op.f("ix_org_api_keys_organisation_id"), "org_api_keys", ["organisation_id"], unique=False
    )
    op.create_table(
        "schema_versions",
        sa.Column("schema_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("definition_json", sa.JSON(), nullable=False),
        sa.Column("published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deprecated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schema_id"], ["schemas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "schema_id",
            "version",
            "organisation_id",
            name="uq_schema_versions_schema_version_organisation",
        ),
        sa.UniqueConstraint("schema_id", "version", name="uq_schema_versions_schema_version"),
    )
    op.create_index(
        op.f("ix_schema_versions_organisation_id"),
        "schema_versions",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schema_versions_schema_id"), "schema_versions", ["schema_id"], unique=False
    )
    op.create_table(
        "stages",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("owner_team_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=10), server_default="org", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("visibility IN ('org', 'team')", name="ck_stages_visibility"),
        sa.CheckConstraint(
            "visibility = 'org' OR owner_team_id IS NOT NULL",
            name="ck_stages_team_owner",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stages_organisation_id"), "stages", ["organisation_id"], unique=False)
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("input_schema_id", sa.UUID(), nullable=False),
        sa.Column("input_schema_version", sa.String(length=50), nullable=False),
        sa.Column("output_schema_id", sa.UUID(), nullable=False),
        sa.Column("output_schema_version", sa.String(length=50), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("prompt_version_history", sa.JSON(), nullable=False),
        sa.Column("model_backend_id", sa.UUID(), nullable=False),
        sa.Column("connector_type_refs", sa.JSON(), nullable=False),
        sa.Column("evals", sa.JSON(), nullable=True),
        sa.Column("retry_policy", sa.JSON(), nullable=False),
        sa.Column("token_budget", sa.Integer(), nullable=True),
        sa.Column("library_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["input_schema_id", "input_schema_version", "organisation_id"],
            [
                "schema_versions.schema_id",
                "schema_versions.version",
                "schema_versions.organisation_id",
            ],
            name="fk_agents_input_schema_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["library_id"], ["library_primitives.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_backend_id"], ["model_backends.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["output_schema_id", "output_schema_version", "organisation_id"],
            [
                "schema_versions.schema_id",
                "schema_versions.version",
                "schema_versions.organisation_id",
            ],
            name="fk_agents_output_schema_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_organisation_id"), "agents", ["organisation_id"], unique=False)
    op.create_table(
        "pipelines",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("stage_id", sa.UUID(), nullable=True),
        sa.Column("owner_team_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=10), server_default="org", nullable=False),
        sa.Column("max_concurrent_runs", sa.Integer(), server_default="5", nullable=False),
        sa.Column("lock_wait_timeout_seconds", sa.Integer(), server_default="300", nullable=False),
        sa.Column("node_timeout_seconds", sa.Integer(), server_default="300", nullable=False),
        sa.Column("run_context_defaults", sa.JSON(), nullable=False),
        sa.Column("default_feedback_handler", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("visibility IN ('org', 'team')", name="ck_pipelines_visibility"),
        sa.CheckConstraint(
            "visibility = 'org' OR owner_team_id IS NOT NULL",
            name="ck_pipelines_team_owner",
        ),
        sa.CheckConstraint(
            "lock_wait_timeout_seconds BETWEEN 30 AND 3600", name="ck_pipelines_lock_wait_timeout"
        ),
        sa.CheckConstraint("max_concurrent_runs > 0", name="ck_pipelines_max_concurrent_runs"),
        sa.CheckConstraint("node_timeout_seconds > 0", name="ck_pipelines_node_timeout"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["stage_id"], ["stages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipelines_organisation_id"), "pipelines", ["organisation_id"], unique=False
    )
    op.create_table(
        "pipeline_edges",
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("source_node_id", sa.UUID(), nullable=False),
        sa.Column("target_node_id", sa.UUID(), nullable=False),
        sa.Column("edge_type", sa.String(), server_default="normal", nullable=False),
        sa.Column("hitl_gate_config", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("edge_type IN ('normal', 'reject')", name="ck_pipeline_edges_type"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pipeline_id",
            "source_node_id",
            "target_node_id",
            "edge_type",
            name="uq_pipeline_edges_path",
        ),
    )
    op.create_index(
        op.f("ix_pipeline_edges_organisation_id"),
        "pipeline_edges",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_edges_pipeline_id"), "pipeline_edges", ["pipeline_id"], unique=False
    )
    op.create_table(
        "pipeline_snapshots",
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("graph_json", sa.JSON(), nullable=False),
        sa.Column("connector_bindings_json", sa.JSON(), nullable=False),
        sa.Column("schema_pins_json", sa.JSON(), nullable=False),
        sa.Column("prompt_pins_json", sa.JSON(), nullable=False),
        sa.Column("model_backend_pins_json", sa.JSON(), nullable=False),
        sa.Column("run_context_defaults", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pipeline_id", "snapshot_version", name="uq_pipeline_snapshot_version"),
    )
    op.create_index(
        op.f("ix_pipeline_snapshots_organisation_id"),
        "pipeline_snapshots",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_snapshots_pipeline_id"),
        "pipeline_snapshots",
        ["pipeline_id"],
        unique=False,
    )
    op.create_table(
        "triggers",
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("trigger_type", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("max_concurrent_runs", sa.Integer(), server_default="1", nullable=False),
        sa.Column("daily_spend_limit", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trigger_type IN ('manual', 'webhook', 'cron', 'polling', 'agent_signal')",
            name="ck_triggers_type",
        ),
        sa.CheckConstraint("max_concurrent_runs > 0", name="ck_triggers_max_concurrent_runs"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_triggers_organisation_id"), "triggers", ["organisation_id"], unique=False
    )
    op.create_index(op.f("ix_triggers_pipeline_id"), "triggers", ["pipeline_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("trigger_id", sa.UUID(), nullable=True),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="pending", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_requested", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("total_cost_usd", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("error_code", sa.String(length=255), nullable=True),
        sa.Column("langgraph_thread_id", sa.String(length=512), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'awaiting_human', 'claimed', "
            "'waiting_for_lock', 'complete', 'failed', 'cancelled')",
            name="ck_runs_status",
        ),
        sa.CheckConstraint(
            "trigger_type IN ('manual', 'webhook', 'cron', 'polling', 'agent_signal')",
            name="ck_runs_trigger_type",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["pipeline_snapshots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["trigger_id"], ["triggers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("langgraph_thread_id"),
    )
    op.create_index(op.f("ix_runs_organisation_id"), "runs", ["organisation_id"], unique=False)
    op.create_index(op.f("ix_runs_pipeline_id"), "runs", ["pipeline_id"], unique=False)
    op.create_table(
        "webhook_dedup_hashes",
        sa.Column("trigger_id", sa.UUID(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trigger_id"], ["triggers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trigger_id", "payload_hash", name="uq_webhook_dedup_trigger_hash"),
    )
    op.create_index(
        op.f("ix_webhook_dedup_hashes_expires_at"),
        "webhook_dedup_hashes",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_dedup_hashes_organisation_id"),
        "webhook_dedup_hashes",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_dedup_hashes_trigger_id"),
        "webhook_dedup_hashes",
        ["trigger_id"],
        unique=False,
    )
    op.create_table(
        "hitl_claims",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("gate_id", sa.String(length=255), nullable=False),
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("claimed_by", sa.UUID(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["claimed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "gate_id", name="uq_hitl_claims_run_gate"),
    )
    op.create_index(
        op.f("ix_hitl_claims_organisation_id"), "hitl_claims", ["organisation_id"], unique=False
    )
    op.create_index(
        op.f("ix_hitl_claims_pipeline_id"), "hitl_claims", ["pipeline_id"], unique=False
    )
    op.create_index(op.f("ix_hitl_claims_run_id"), "hitl_claims", ["run_id"], unique=False)
    op.create_table(
        "notification_delivery_log",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("endpoint_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=2000), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_delivery_log_endpoint_id"),
        "notification_delivery_log",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_delivery_log_event_type"),
        "notification_delivery_log",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_delivery_log_organisation_id"),
        "notification_delivery_log",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_delivery_log_run_id"),
        "notification_delivery_log",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "trigger_events",
        sa.Column("trigger_id", sa.UUID(), nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("raw_payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("validation_result", sa.String(length=50), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("error_detail", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_result IN ('passed', 'hmac_failed', 'schema_validation_failed', "
            "'deduplicated', 'concurrency_limit_reached', 'timestamp_expired', "
            "'validation_failed', 'rate_limited')",
            name="ck_trigger_events_validation_result",
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["trigger_id"], ["triggers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trigger_events_organisation_id"),
        "trigger_events",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trigger_events_trigger_id"), "trigger_events", ["trigger_id"], unique=False
    )
    op.create_table(
        "webhook_payloads",
        sa.Column("trigger_event_id", sa.UUID(), nullable=False),
        sa.Column("payload_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trigger_event_id"], ["trigger_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_payloads_expires_at"), "webhook_payloads", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_payloads_organisation_id"),
        "webhook_payloads",
        ["organisation_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    _create_tenant_reference_guards()
    _create_library_fork_guard()


def downgrade() -> None:

    op.execute(sa.text("DROP FUNCTION enforce_library_fork_provenance() CASCADE"))
    op.execute(sa.text("DROP FUNCTION enforce_same_organisation() CASCADE"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_payloads_organisation_id"), table_name="webhook_payloads")
    op.drop_index(op.f("ix_webhook_payloads_expires_at"), table_name="webhook_payloads")
    op.drop_table("webhook_payloads")
    op.drop_index(op.f("ix_trigger_events_trigger_id"), table_name="trigger_events")
    op.drop_index(op.f("ix_trigger_events_organisation_id"), table_name="trigger_events")
    op.drop_table("trigger_events")
    op.drop_index(
        op.f("ix_notification_delivery_log_run_id"), table_name="notification_delivery_log"
    )
    op.drop_index(
        op.f("ix_notification_delivery_log_organisation_id"), table_name="notification_delivery_log"
    )
    op.drop_index(
        op.f("ix_notification_delivery_log_event_type"), table_name="notification_delivery_log"
    )
    op.drop_index(
        op.f("ix_notification_delivery_log_endpoint_id"), table_name="notification_delivery_log"
    )
    op.drop_table("notification_delivery_log")
    op.drop_index(op.f("ix_hitl_claims_run_id"), table_name="hitl_claims")
    op.drop_index(op.f("ix_hitl_claims_pipeline_id"), table_name="hitl_claims")
    op.drop_index(op.f("ix_hitl_claims_organisation_id"), table_name="hitl_claims")
    op.drop_table("hitl_claims")
    op.drop_index(op.f("ix_webhook_dedup_hashes_trigger_id"), table_name="webhook_dedup_hashes")
    op.drop_index(
        op.f("ix_webhook_dedup_hashes_organisation_id"), table_name="webhook_dedup_hashes"
    )
    op.drop_index(op.f("ix_webhook_dedup_hashes_expires_at"), table_name="webhook_dedup_hashes")
    op.drop_table("webhook_dedup_hashes")
    op.drop_index(op.f("ix_runs_pipeline_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_organisation_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_triggers_pipeline_id"), table_name="triggers")
    op.drop_index(op.f("ix_triggers_organisation_id"), table_name="triggers")
    op.drop_table("triggers")
    op.drop_index(op.f("ix_pipeline_snapshots_pipeline_id"), table_name="pipeline_snapshots")
    op.drop_index(op.f("ix_pipeline_snapshots_organisation_id"), table_name="pipeline_snapshots")
    op.drop_table("pipeline_snapshots")
    op.drop_index(op.f("ix_pipeline_edges_pipeline_id"), table_name="pipeline_edges")
    op.drop_index(op.f("ix_pipeline_edges_organisation_id"), table_name="pipeline_edges")
    op.drop_table("pipeline_edges")
    op.drop_index(op.f("ix_pipelines_organisation_id"), table_name="pipelines")
    op.drop_table("pipelines")
    op.drop_index(op.f("ix_agents_organisation_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_stages_organisation_id"), table_name="stages")
    op.drop_table("stages")
    op.drop_index(op.f("ix_schema_versions_schema_id"), table_name="schema_versions")
    op.drop_index(op.f("ix_schema_versions_organisation_id"), table_name="schema_versions")
    op.drop_table("schema_versions")
    op.drop_index(op.f("ix_org_api_keys_organisation_id"), table_name="org_api_keys")
    op.drop_table("org_api_keys")
    op.drop_index(op.f("ix_model_backends_organisation_id"), table_name="model_backends")
    op.drop_table("model_backends")
    op.drop_index(op.f("ix_library_primitives_organisation_id"), table_name="library_primitives")
    op.drop_table("library_primitives")
    op.drop_index(op.f("ix_connector_instances_organisation_id"), table_name="connector_instances")
    op.drop_index(
        op.f("ix_connector_instances_connector_type_id"), table_name="connector_instances"
    )
    op.drop_table("connector_instances")
    op.drop_index(op.f("ix_teams_organisation_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_schemas_organisation_id"), table_name="schemas")
    op.drop_table("schemas")
    op.drop_index(op.f("ix_audit_events_organisation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_organisation_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_org_daily_run_counts_organisation_id"), table_name="org_daily_run_counts"
    )
    op.drop_table("org_daily_run_counts")
    op.drop_table("organisations")
    # ### end Alembic commands ###
