name: Qlty Analysis (baseline vs main)

on:
  workflow_dispatch:

jobs:
  qlty:
    name: Qlty scan
    runs-on: ubicloud-standard-2
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - name: Install Qlty CLI
        uses: qltysh/qlty-action/install@08a0a862c159eae9b9003081da6663d96efef637

      - name: Run Qlty check
        run: qlty check --upstream origin/main
        env:
          QLTY_API_KEY: ${{ secrets.QLTY_API_KEY }}
